version: 0.2

env:
  variables:
    LAMBDA_BUCKET: "cloud-assignment3-code-bucket" 

phases:
  install:
    runtime-versions:
      python: 3.12
  
  pre_build:
    commands:
      - echo "Running pre-build commands..."

  build:
    commands:
      - ls
      - pwd
      - echo "Building Lambda function 1..."
      - cd photoSearchEngine/custom_lambdas/
      - pip install -r requirements.txt -t ./
      - zip -r ../../index-photos.zip *
      - zip -r ../../search-photos.zip *
      - aws s3 cp ../../index-photos.zip s3://$LAMBDA_BUCKET --output=text
      - aws s3 cp ../../search-photos.zip s3://$LAMBDA_BUCKET --output=text

artifacts:
  files:
    - index-photos.zip
    - search-photos.zip
    - photoSearchEngine/scripts/lambda.yaml
    - photoSearchEngine/scripts/buckets.yaml