version: '3'
services:
  app:
    image: todo_app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
