apiVersion: v1
kind: ReplicationController
metadata:
  name: flask-app-rc
spec:
  replicas: 3
  selector:
    app: flask-rc-app
  template:
    metadata:
      labels:
        app: flask-rc-app
    spec:
      containers:
      - name: flask
        image: 637423495437.dkr.ecr.us-west-2.amazonaws.com/todo-flask-app:v2
        ports:
        - containerPort: 5000
