global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'todo-app'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_container_name]
        action: keep
        regex: todo-app-container
